version: 2

jobs:
  test:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout

      - run: yarn

      - run:
          name: Run tests
          command: |
            npm run test

  publishPackage:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout

      - run:
          name: Publish package
          command: npm publish --userconfig=.npmrc-auth

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publishPackage:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - test
